extends Node


#func _ready() -> void:
	#SteamHandler.achievement_get("a_glaze_get")
	#SteamHandler.achievement_get("a_pot_lid_get")
	#SteamHandler.achievement_get("a_forsaken_defeat")
	#SteamHandler.achievement_get("a_lenore_favor")
	#SteamHandler.achievement_get("a_efficiency_up")
	#SteamHandler.achievement_get("a_efficiency_max")
	#SteamHandler.achievement_get("a_capacity_up")
	#SteamHandler.achievement_get("a_capacity_max")
	#SteamHandler.achievement_get("a_intensity_up")
	#SteamHandler.achievement_get("a_intensity_max")
	#SteamHandler.achievement_get("a_ngplus_journal_get")
	#SteamHandler.achievement_get("a_flawed_vessel_stump")
	#SteamHandler.achievement_get("a_gaping_jawer_defeat")
	#SteamHandler.achievement_get("a_flawed_vessel_censer")
	#SteamHandler.achievement_get("a_flawed_vessel_amphora")
	#SteamHandler.achievement_get("a_humanity_obtained")
	#SteamHandler.achievement_get("a_bell_gold_rung")
	#SteamHandler.achievement_get("a_bell_silver_rung")
	#SteamHandler.achievement_get("a_new_game")
	#SteamHandler.achievement_get("a_ending_bad")
	#SteamHandler.achievement_get("a_ending_good")
	#SteamHandler.achievement_get("a_ending_secret")
	#SteamHandler.achievement_get("a_ngplus_reset_accept")
	#SteamHandler.achievement_get("a_ngplus_reset_deny")
	#SteamHandler.achievement_get("a_lenore_defeat")
	#SteamHandler.achievement_get("a_ebon_vessel_defeat")
	#SteamHandler.achievement_get("a_frenzied_growth_defeat")
	#SteamHandler.achievement_get("a_abyssoul_defeat")
