extends Node
@export_enum("unlock_all","lock_all") var achievement_test_setting: String = "unlock_all"

##This won't work unless a player character node is added to the scene btw
func _ready() -> void:
	if achievement_test_setting == "unlock_all":
		GameState.target_player.anim_achievement("a_glaze_get")
		GameState.target_player.anim_achievement("a_pot_lid_get")
		GameState.target_player.anim_achievement("a_forsaken_defeat")
		GameState.target_player.anim_achievement("a_lenore_favor")
		GameState.target_player.anim_achievement("a_efficiency_up")
		GameState.target_player.anim_achievement("a_efficiency_max")
		GameState.target_player.anim_achievement("a_capacity_up")
		GameState.target_player.anim_achievement("a_capacity_max")
		GameState.target_player.anim_achievement("a_intensity_up")
		GameState.target_player.anim_achievement("a_intensity_max")
		GameState.target_player.anim_achievement("a_ngplus_journal_get")
		GameState.target_player.anim_achievement("a_flawed_vessel_stump")
		GameState.target_player.anim_achievement("a_gaping_jawer_defeat")
		GameState.target_player.anim_achievement("a_flawed_vessel_censer")
		GameState.target_player.anim_achievement("a_flawed_vessel_amphora")
		GameState.target_player.anim_achievement("a_humanity_obtained")
		GameState.target_player.anim_achievement("a_bell_gold_rung")
		GameState.target_player.anim_achievement("a_bell_silver_rung")
		GameState.target_player.anim_achievement("a_new_game")
		GameState.target_player.anim_achievement("a_ending_bad")
		GameState.target_player.anim_achievement("a_ending_good")
		GameState.target_player.anim_achievement("a_ending_secret")
		GameState.target_player.anim_achievement("a_ngplus_reset_accept")
		GameState.target_player.anim_achievement("a_ngplus_reset_deny")
		GameState.target_player.anim_achievement("a_lenore_defeat")
		GameState.target_player.anim_achievement("a_ebon_vessel_defeat")
		GameState.target_player.anim_achievement("a_frenzied_growth_defeat")
		GameState.target_player.anim_achievement("a_abyssoul_defeat")
	else:
		SteamHandler.achievement_reset("a_glaze_get")
		SteamHandler.achievement_reset("a_pot_lid_get")
		SteamHandler.achievement_reset("a_forsaken_defeat")
		SteamHandler.achievement_reset("a_lenore_favor")
		SteamHandler.achievement_reset("a_efficiency_up")
		SteamHandler.achievement_reset("a_efficiency_max")
		SteamHandler.achievement_reset("a_capacity_up")
		SteamHandler.achievement_reset("a_capacity_max")
		SteamHandler.achievement_reset("a_intensity_up")
		SteamHandler.achievement_reset("a_intensity_max")
		SteamHandler.achievement_reset("a_ngplus_journal_get")
		SteamHandler.achievement_reset("a_flawed_vessel_stump")
		SteamHandler.achievement_reset("a_gaping_jawer_defeat")
		SteamHandler.achievement_reset("a_flawed_vessel_censer")
		SteamHandler.achievement_reset("a_flawed_vessel_amphora")
		SteamHandler.achievement_reset("a_humanity_obtained")
		SteamHandler.achievement_reset("a_bell_gold_rung")
		SteamHandler.achievement_reset("a_bell_silver_rung")
		SteamHandler.achievement_reset("a_new_game")
		SteamHandler.achievement_reset("a_ending_bad")
		SteamHandler.achievement_reset("a_ending_good")
		SteamHandler.achievement_reset("a_ending_secret")
		SteamHandler.achievement_reset("a_ngplus_reset_accept")
		SteamHandler.achievement_reset("a_ngplus_reset_deny")
		SteamHandler.achievement_reset("a_lenore_defeat")
		SteamHandler.achievement_reset("a_ebon_vessel_defeat")
		SteamHandler.achievement_reset("a_frenzied_growth_defeat")
		SteamHandler.achievement_reset("a_abyssoul_defeat")
		Sound.respawn() ##placeholder
