extends Node

##This won't work unless a player character node is added to the scene btw
#func _ready() -> void:
	#GameState.target_player.anim_achievement("a_glaze_get")
	#GameState.target_player.anim_achievement("a_pot_lid_get")
	#GameState.target_player.anim_achievement("a_forsaken_defeat")
	#GameState.target_player.anim_achievement("a_lenore_favor")
	#GameState.target_player.anim_achievement("a_efficiency_up")
	#GameState.target_player.anim_achievement("a_efficiency_max")
	#GameState.target_player.anim_achievement("a_capacity_up")
	#GameState.target_player.anim_achievement("a_capacity_max")
	#GameState.target_player.anim_achievement("a_intensity_up")
	#GameState.target_player.anim_achievement("a_intensity_max")
	#GameState.target_player.anim_achievement("a_ngplus_journal_get")
	#GameState.target_player.anim_achievement("a_flawed_vessel_stump")
	#GameState.target_player.anim_achievement("a_gaping_jawer_defeat")
	#GameState.target_player.anim_achievement("a_flawed_vessel_censer")
	#GameState.target_player.anim_achievement("a_flawed_vessel_amphora")
	#GameState.target_player.anim_achievement("a_humanity_obtained")
	#GameState.target_player.anim_achievement("a_bell_gold_rung")
	#GameState.target_player.anim_achievement("a_bell_silver_rung")
	#GameState.target_player.anim_achievement("a_new_game")
	#GameState.target_player.anim_achievement("a_ending_bad")
	#GameState.target_player.anim_achievement("a_ending_good")
	#GameState.target_player.anim_achievement("a_ending_secret")
	#GameState.target_player.anim_achievement("a_ngplus_reset_accept")
	#GameState.target_player.anim_achievement("a_ngplus_reset_deny")
	#GameState.target_player.anim_achievement("a_lenore_defeat")
	#GameState.target_player.anim_achievement("a_ebon_vessel_defeat")
	#GameState.target_player.anim_achievement("a_frenzied_growth_defeat")
	#GameState.target_player.anim_achievement("a_abyssoul_defeat")
